<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Results (powered by Planemo)"
           tests="64"
           errors="10"
           failures="5"
           skip="0">
    
    <testcase classname="bcftools_filter (Test #1)" name="0" time="12.83678150177002">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 12.83678150177002, "tool_id": "bcftools_filter", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #2)" name="1" time="44.1246657371521">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #11)" name="10" time="38.849462032318115">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #3)" name="2" time="36.53516960144043">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #4)" name="3" time="37.206825494766235">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #5)" name="4" time="37.60148620605469">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #6)" name="5" time="37.269336462020874">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #7)" name="6" time="39.96031975746155">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #8)" name="7" time="37.404613733291626">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #9)" name="8" time="37.443774461746216">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #10)" name="9" time="28.251978874206543">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input_file": {   "id": "b2ac27be18745d0d",   "src": "hda"  },  "output_type": "v",  "sec_restrict|include": "FMT/GT=\"0/0\" \u0026\u0026 AC[*]=2",  "sec_restrict|regions_overlap": "1" }, "job": {  "command_line": "export BCFTOOLS_PLUGINS=`which bcftools | sed \u0027s,bin/bcftools,libexec/bcftools,\u0027`;     bgzip -c \u0027/galaxy/server/database/objects/d/8/5/dataset_d8536e9f-53b6-4727-a8b4-470dd88b9116.dat\u0027 \u003e input.vcf.gz \u0026\u0026 bcftools index input.vcf.gz \u0026\u0026            bcftools filter     --regions-overlap 1         --include \u0027FMT/GT=\"0/0\" \u0026\u0026 AC[*]=2\u0027      --output-type \u0027v\u0027   --threads ${GALAXY_SLOTS:-4}    input.vcf.gz  \u003e \u0027/galaxy/server/database/objects/9/3/7/dataset_937901e1-e7ec-410f-87a0-752e71f54e46.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-24T01:21:31.137182",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-xfgqh",  "galaxy_version": "24.1",  "handler": null,  "history_id": "3b4cd3e794c37e3e",  "id": "bed5c3e21f01a6ef",  "inputs": {   "input_file": {    "id": "b2ac27be18745d0d",    "src": "hda",    "uuid": "d8536e9f-53b6-4727-a8b4-470dd88b9116"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output_file": {    "id": "bed5c3e21f01a6ef",    "src": "hda",    "uuid": "937901e1-e7ec-410f-87a0-752e71f54e46"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "output_type": "\"v\"",   "sec_filter": "{\"IndelGap\": \"\", \"SnpGap\": \"\", \"conditional_soft_filter\": {\"__current_case__\": 0, \"selector\": \"disabled\"}, \"mode\": null, \"select_set_GTs\": null}",   "sec_restrict": "{\"exclude\": null, \"include\": \"FMT/GT=\\\"0/0\\\" \u0026\u0026 AC[*]=2\", \"regions\": {\"__current_case__\": 0, \"regions_src\": \"__none__\"}, \"regions_overlap\": \"1\", \"targets\": {\"__current_case__\": 0, \"targets_src\": \"__none__\"}, \"targets_overlap\": null}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/bcftools_filter/bcftools_filter/1.15.1+galaxy4",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-24T01:21:36.817271",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/bcftools_filter/bcftools_filter/1.15.1+galaxy4, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/bcftools_filter/bcftools_filter/1.15.1+galaxy4, exit_code: None, stderr: ." ], "status": "failure", "test_index": 9, "time_seconds": 28.251978874206543, "tool_id": "bcftools_filter", "tool_version": "1.15.1+galaxy4"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #1)" name="0" time="48.19115376472473">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 1 samples in 1 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #2)" name="1" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 1, "tool_id": "bcftools_mpileup", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #3)" name="2" time="40.11968421936035">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 1 samples in 1 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #4)" name="3" time="50.52840781211853">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [warning] tag DV functional, but deprecated. Please switch to `AD` in future.[mpileup] 3 samples in 3 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #5)" name="4" time="51.236308574676514">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [warning] tag DV functional, but deprecated. Please switch to `AD` in future.[mpileup] 3 samples in 3 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #6)" name="5" time="50.477564334869385">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 3 samples in 3 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #7)" name="6" time="40.15596675872803">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 1 samples in 1 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #1)" name="0" time="99.37860560417175">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #2)" name="1" time="38.37948489189148">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #3)" name="2" time="40.130382776260376">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #4)" name="3" time="36.563440799713135">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="deeptools_bam_pe_fragmentsize (Test #1)" name="0" time="66.97945380210876">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="deeptools_bam_pe_fragmentsize (Test #2)" name="1" time="54.70925164222717">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #1)" name="0" time="54.68240308761597">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #2)" name="1" time="40.9356324672699">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #3)" name="2" time="13.206644535064697">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 2, "time_seconds": 13.206644535064697, "tool_id": "freebayes", "tool_version": "1.3.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="freebayes (Test #4)" name="3" time="39.79373598098755">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #5)" name="4" time="39.82111358642578">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #6)" name="5" time="23.153977870941162">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 5, "time_seconds": 23.153977870941162, "tool_id": "freebayes", "tool_version": "1.3.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="freebayes (Test #7)" name="6" time="31.049779891967773">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "coverage_options|coverage_options_selector": "set",  "coverage_options|skip_coverage": "100",  "options_type|options_type_selector": "simple",  "reference_source|batchmode|input_bams": {   "id": "7a358969263a1b48",   "src": "hda"  },  "reference_source|batchmode|processmode": "individual",  "reference_source|ref_file": {   "id": "d65490ed2404b9c8",   "src": "hda"  },  "reference_source|reference_source_selector": "history" }, "job": {  "command_line": "ln -s -f \u0027/galaxy/server/database/objects/e/0/4/dataset_e042051e-b51d-4c50-aeb5-e51458d02222.dat\u0027 \u0027localref.fa\u0027 \u0026\u0026 samtools faidx \u0027localref.fa\u0027 2\u003e\u00261 || echo \"Error running samtools faidx for FreeBayes\" \u003e\u00262 \u0026\u0026   ln -s -f \u0027/galaxy/server/database/objects/5/f/0/dataset_5f001e0b-8fda-4067-a3b0-1c272430fe63.dat\u0027 \u0027b_0.bam\u0027 \u0026\u0026 ln -s -f \u0027/galaxy/server/database/objects/_metadata_files/9/8/f/metadata_98f610a3-63ef-42f0-9d10-f5a805d5178f.dat\u0027 \u0027b_0.bam.bai\u0027 \u0026\u0026   samtools view -H b_0.bam| grep \u0027^@SQ\u0027 | cut -f 2- | awk \u0027{ gsub(\"^SN:\",\"\",$1); gsub(\"^LN:\",\"\",$2); print $1\"\\t0\\t\"$2; }\u0027 \u003e\u003e regions_all.bed \u0026\u0026  sort -u regions_all.bed \u003e regions_uniq.bed \u0026\u0026  mkdir vcf_output failed_alleles trace \u0026\u0026   for i in `cat regions_uniq.bed | awk \u0027{print $1\":\"$2\"..\"$3}\u0027`; do echo \"   freebayes  --region \u0027$i\u0027  --bam \u0027b_0.bam\u0027 --fasta-reference \u0027localref.fa\u0027  --vcf \u0027./vcf_output/part_$i.vcf\u0027   --min-coverage 0 --skip-coverage 100 --limit-coverage 0    \"; done \u003e freebayes_commands.sh \u0026\u0026  cat freebayes_commands.sh | parallel --will-cite -j ${GALAXY_SLOTS:-1} \u0026\u0026  grep \"^#\" \"./vcf_output/part_$i.vcf\" \u003e header.txt \u0026\u0026  for i in `cat regions_uniq.bed | awk \u0027{print $1\":\"$2\"..\"$3}\u0027`; do cat \"./vcf_output/part_$i.vcf\" | grep -v \"^#\" || true ; done | sort -k1,1 -k2,2n -k5,5 -u | cat header.txt - \u003e \u0027/galaxy/server/database/objects/8/7/6/dataset_876fb436-aae3-4fb7-bf2b-12a03851bdf1.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-24T01:37:03.295905",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-jc4pf",  "galaxy_version": "24.1",  "handler": null,  "history_id": "3b4cd3e794c37e3e",  "id": "b64973c0a9cc1018",  "inputs": {   "reference_source|batchmode|input_bams": {    "id": "7a358969263a1b48",    "src": "hda",    "uuid": "5f001e0b-8fda-4067-a3b0-1c272430fe63"   },   "reference_source|ref_file": {    "id": "d65490ed2404b9c8",    "src": "hda",    "uuid": "e042051e-b51d-4c50-aeb5-e51458d02222"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output_vcf": {    "id": "a5f74b2134ddfb27",    "src": "hda",    "uuid": "876fb436-aae3-4fb7-bf2b-12a03851bdf1"   }  },  "params": {   "__input_ext": "\"bam\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "coverage_options": "{\"__current_case__\": 0, \"coverage_options_selector\": \"set\", \"limit_coverage\": \"0\", \"min_coverage\": \"0\", \"skip_coverage\": \"100\"}",   "dbkey": "\"?\"",   "options_type": "{\"__current_case__\": 1, \"options_type_selector\": \"simple\"}",   "reference_source": "{\"__current_case__\": 1, \"batchmode\": {\"__current_case__\": 0, \"input_bams\": {\"values\": [{\"id\": 138, \"src\": \"hda\"}]}, \"processmode\": \"individual\"}, \"ref_file\": {\"values\": [{\"id\": 139, \"src\": \"hda\"}]}, \"reference_source_selector\": \"history\"}",   "target_limit_type": "{\"__current_case__\": 0, \"target_limit_type_selector\": \"do_not_limit\"}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/freebayes/freebayes/1.3.8+galaxy0",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-24T01:37:09.259869",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/freebayes/freebayes/1.3.8+galaxy0, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/freebayes/freebayes/1.3.8+galaxy0, exit_code: None, stderr: ." ], "status": "failure", "test_index": 6, "time_seconds": 31.049779891967773, "tool_id": "freebayes", "tool_version": "1.3.8+galaxy0"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #8)" name="7" time="13.619399070739746">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 7, "time_seconds": 13.619399070739746, "tool_id": "freebayes", "tool_version": "1.3.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #1)" name="0" time="48.12053346633911">
        
            
            <system-out><![CDATA[
            {"n_targets": 1,"n_bootstraps": 0,"n_processed": 100,"n_pseudoaligned": 100,"n_unique": 100,"p_pseudoaligned": 100.0,"p_unique": 100.0,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug 24 01:37:59 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . /galaxy/server/database/objects/4/8/4/dataset_484d89ce-8555-474a-bc23-a1728639989d.dat /galaxy/server/database/objects/c/e/5/dataset_ce5644be-7541-46df-a1f5-e21a1d3b3acb.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 1[index] number of k-mers: 16,269[index] number of equivalence classes: 1[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/4/8/4/dataset_484d89ce-8555-474a-bc23-a1728639989d.dat                             /galaxy/server/database/objects/c/e/5/dataset_ce5644be-7541-46df-a1f5-e21a1d3b3acb.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 100 reads, 100 reads pseudoaligned[quant] estimated average fragment length: 499.12[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 52 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #2)" name="1" time="23.247189044952393">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 1, "time_seconds": 23.247189044952393, "tool_id": "kallisto_quant", "tool_version": "0.48.0+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #3)" name="2" time="44.68778133392334">
        
            
            <system-out><![CDATA[
            {"n_targets": 1,"n_bootstraps": 0,"n_processed": 100,"n_pseudoaligned": 100,"n_unique": 100,"p_pseudoaligned": 100.0,"p_unique": 100.0,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug 24 01:39:07 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . /galaxy/server/database/objects/0/b/4/dataset_0b498033-e70c-4a86-92c3-4acbeb384c2b.dat /galaxy/server/database/objects/4/9/e/dataset_49e4ca19-e5da-46a4-a9ef-79c9c146a964.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 1[index] number of k-mers: 16,269[index] number of equivalence classes: 1[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/0/b/4/dataset_0b498033-e70c-4a86-92c3-4acbeb384c2b.dat                             /galaxy/server/database/objects/4/9/e/dataset_49e4ca19-e5da-46a4-a9ef-79c9c146a964.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 100 reads, 100 reads pseudoaligned[quant] estimated average fragment length: 499.12[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 52 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #4)" name="3" time="39.936418294906616">
        
            
            <system-out><![CDATA[
            {"n_targets": 1,"n_bootstraps": 0,"n_processed": 100,"n_pseudoaligned": 100,"n_unique": 100,"p_pseudoaligned": 100.0,"p_unique": 100.0,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug 24 01:39:47 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . --single --fragment-length 200 --sd 20 /galaxy/server/database/objects/8/c/7/dataset_8c78f870-67c8-400f-92db-471f36df4ef2.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers [quant] fragment length distribution is truncated gaussian with mean = 200, sd = 20[index] k-mer length: 31[index] number of targets: 1[index] number of k-mers: 16,269[index] number of equivalence classes: 1[quant] running in single-end mode[quant] will process file 1: /galaxy/server/database/objects/8/c/7/dataset_8c78f870-67c8-400f-92db-471f36df4ef2.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 100 reads, 100 reads pseudoaligned[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 52 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #5)" name="4" time="44.78755211830139">
        
            
            <system-out><![CDATA[
            {"n_targets": 1,"n_bootstraps": 0,"n_processed": 200,"n_pseudoaligned": 200,"n_unique": 200,"p_pseudoaligned": 100.0,"p_unique": 100.0,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug 24 01:40:32 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --pseudobam -o . /galaxy/server/database/objects/b/d/a/dataset_bdad2c22-24e1-44ff-baa0-036030853a98.dat /galaxy/server/database/objects/6/0/b/dataset_60bc0ede-613d-4f24-bdb4-3a1543962834.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 15 contigs and contains 16670 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 1[index] number of k-mers: 16,670[index] number of equivalence classes: 1[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/b/d/a/dataset_bdad2c22-24e1-44ff-baa0-036030853a98.dat                             /galaxy/server/database/objects/6/0/b/dataset_60bc0ede-613d-4f24-bdb4-3a1543962834.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 200 reads, 200 reads pseudoaligned[quant] estimated average fragment length: 500.01[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 52 rounds[  bam] writing pseudoalignments to BAM format .. done
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #6)" name="5" time="24.693591117858887">
        
            <error type="error" message="parameter 'index': an invalid option (None) was selected, please verify"><![CDATA[
                { "dynamic_param_error": true, "execution_problem": "parameter \u0027index\u0027: an invalid option (None) was selected, please verify", "inputs": {  "pseudobam": true,  "single_paired|forward": {   "id": "8eacafd997150160",   "src": "hda"  },  "single_paired|reverse": {   "id": "2a19c68a2f4cebc4",   "src": "hda"  },  "single_paired|single_paired_selector": "paired_single" }, "status": "error", "test_index": 5, "time_seconds": 24.693591117858887, "tool_id": "kallisto_quant", "tool_version": "0.48.0+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #7)" name="6" time="36.47043466567993">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "fusion": true,  "reference_transcriptome|reference": {   "id": "c8fd969b5d7f99c1",   "src": "hda"  },  "reference_transcriptome|reference_transcriptome_source": "history",  "single_paired|forward": {   "id": "3979fc2fd8b997f7",   "src": "hda"  },  "single_paired|reverse": {   "id": "afa40654723032c2",   "src": "hda"  },  "single_paired|single_paired_selector": "paired_single" }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/1/7/1/dataset_1713d4f1-655a-4e4c-ac1f-3ffaf7cf6bc5.dat\u0027 reference.fa \u0026\u0026 kallisto index reference.fa -i reference.kallisto \u0026\u0026 kallisto quant -i \u0027reference.kallisto\u0027 --bootstrap-samples 0 --seed 42 --fusion --threads ${GALAXY_SLOTS:-1} -o .  \u0027/galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat\u0027 \u0027/galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat\u0027  \u0026\u0026 cat run_info.json",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-24T01:41:40.715125",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-b26jc",  "galaxy_version": "24.1",  "handler": null,  "history_id": "3b4cd3e794c37e3e",  "id": "697834d68cc50567",  "inputs": {   "reference_transcriptome|reference": {    "id": "c8fd969b5d7f99c1",    "src": "hda",    "uuid": "1713d4f1-655a-4e4c-ac1f-3ffaf7cf6bc5"   },   "single_paired|forward": {    "id": "3979fc2fd8b997f7",    "src": "hda",    "uuid": "4fbcf9ca-ee94-4909-a748-f08619b8bc3c"   },   "single_paired|reverse": {    "id": "afa40654723032c2",    "src": "hda",    "uuid": "fc5ae325-bb9e-419f-9ac2-7847f36affdc"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "abundance_h5": {    "id": "99acb862911814bf",    "src": "hda",    "uuid": "a4e484ea-dcdc-461a-88e5-b5303627809a"   },   "abundance_tab": {    "id": "1547a667973679a9",    "src": "hda",    "uuid": "949b2adb-9fcc-43ae-af70-27e1f3e97816"   },   "fusion_output": {    "id": "4c233b1f8aae9172",    "src": "hda",    "uuid": "d69aa8ac-4348-4d83-a6e3-ca00ab5cb677"   }  },  "params": {   "__input_ext": "\"input\"",   "bias": "false",   "bootstrap_samples": "\"0\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/hg38.len\"",   "dbkey": "\"hg38\"",   "fusion": "true",   "genomebam_option": "{\"__current_case__\": 1, \"selector\": \"\"}",   "pseudobam": "false",   "reference_transcriptome": "{\"__current_case__\": 1, \"reference\": {\"values\": [{\"id\": 168, \"src\": \"hda\"}]}, \"reference_transcriptome_source\": \"history\"}",   "seed": "\"42\"",   "single_overhang": "false",   "single_paired": "{\"__current_case__\": 1, \"forward\": {\"values\": [{\"id\": 169, \"src\": \"hda\"}]}, \"lib_type\": \"\", \"reverse\": {\"values\": [{\"id\": 170, \"src\": \"hda\"}]}, \"single_paired_selector\": \"paired_single\"}"  },  "state": "error",  "stderr": "\n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] warning: clipped off poly-A tail (longer than 10)\n        from 7 target sequences\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1179 contigs and contains 216490 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 284\n[index] number of k-mers: 216,490\n[index] number of equivalence classes: 909\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat\n                             /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 744 reads, 368 reads pseudoaligned\n[quant] estimated average fragment length: 140.96\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 210 rounds\n\n",  "stdout": "{\n\t\"n_targets\": 284,\n\t\"n_bootstraps\": 0,\n\t\"n_processed\": 744,\n\t\"n_pseudoaligned\": 368,\n\t\"n_unique\": 263,\n\t\"p_pseudoaligned\": 49.5,\n\t\"p_unique\": 35.3,\n\t\"kallisto_version\": \"0.48.0\",\n\t\"index_version\": 10,\n\t\"start_time\": \"Sun Aug 24 01:41:44 2025\",\n\t\"call\": \"kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --fusion --threads 8 -o . /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat\"\n}\n",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/kallisto_quant/kallisto_quant/0.48.0+galaxy1",  "tool_stderr": "\n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] warning: clipped off poly-A tail (longer than 10)\n        from 7 target sequences\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1179 contigs and contains 216490 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 284\n[index] number of k-mers: 216,490\n[index] number of equivalence classes: 909\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat\n                             /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 744 reads, 368 reads pseudoaligned\n[quant] estimated average fragment length: 140.96\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 210 rounds\n\n",  "tool_stdout": "{\n\t\"n_targets\": 284,\n\t\"n_bootstraps\": 0,\n\t\"n_processed\": 744,\n\t\"n_pseudoaligned\": 368,\n\t\"n_unique\": 263,\n\t\"p_pseudoaligned\": 49.5,\n\t\"p_unique\": 35.3,\n\t\"kallisto_version\": \"0.48.0\",\n\t\"index_version\": 10,\n\t\"start_time\": \"Sun Aug 24 01:41:44 2025\",\n\t\"call\": \"kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --fusion --threads 8 -o . /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat\"\n}\n",  "update_time": "2025-08-24T01:41:47.400214",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/kallisto_quant/kallisto_quant/0.48.0+galaxy1, exit_code: None, stderr: \n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] warning: clipped off poly-A tail (longer than 10)\n        from 7 target sequences\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1179 contigs and contains 216490 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 284\n[index] number of k-mers: 216,490\n[index] number of equivalence classes: 909\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat\n                             /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 744 reads, 368 reads pseudoaligned\n[quant] estimated average fragment length: 140.96\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 210 rounds\n\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/kallisto_quant/kallisto_quant/0.48.0+galaxy1, exit_code: None, stderr: \n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] warning: clipped off poly-A tail (longer than 10)\n        from 7 target sequences\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1179 contigs and contains 216490 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 284\n[index] number of k-mers: 216,490\n[index] number of equivalence classes: 909\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat\n                             /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 744 reads, 368 reads pseudoaligned\n[quant] estimated average fragment length: 140.96\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 210 rounds\n\n." ], "status": "failure", "test_index": 6, "time_seconds": 36.47043466567993, "tool_id": "kallisto_quant", "tool_version": "0.48.0+galaxy1"}
                ]]></error>
            
            <system-out><![CDATA[
            {"n_targets": 284,"n_bootstraps": 0,"n_processed": 744,"n_pseudoaligned": 368,"n_unique": 263,"p_pseudoaligned": 49.5,"p_unique": 35.3,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug 24 01:41:44 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --fusion --threads 8 -o . /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] warning: clipped off poly-A tail (longer than 10)        from 7 target sequences[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1179 contigs and contains 216490 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 284[index] number of k-mers: 216,490[index] number of equivalence classes: 909[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/4/f/b/dataset_4fbcf9ca-ee94-4909-a748-f08619b8bc3c.dat                             /galaxy/server/database/objects/f/c/5/dataset_fc5ae325-bb9e-419f-9ac2-7847f36affdc.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 744 reads, 368 reads pseudoaligned[quant] estimated average fragment length: 140.96[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 210 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #8)" name="7" time="66.74476957321167">
        
            
            <system-out><![CDATA[
            {"n_targets": 15,"n_bootstraps": 0,"n_processed": 10000,"n_pseudoaligned": 10000,"n_unique": 6937,"p_pseudoaligned": 100.0,"p_unique": 69.4,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug 24 01:42:40 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . --genomebam --gtf /galaxy/server/database/objects/d/3/d/dataset_d3db965b-0f6e-4819-b6a3-7dcf56d3b9aa.dat --chromosomes /galaxy/server/database/objects/b/1/3/dataset_b132eca8-b531-4351-b809-0146c1da67b0.dat /galaxy/server/database/objects/4/9/2/dataset_4922b943-9afa-4b54-9e27-591866bc523f.dat /galaxy/server/database/objects/0/a/4/dataset_0a442340-e9ec-4c25-ad72-3fd80287970a.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 23 contigs and contains 18902 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 15[index] number of k-mers: 18,902[index] number of equivalence classes: 22[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/4/9/2/dataset_4922b943-9afa-4b54-9e27-591866bc523f.dat                             /galaxy/server/database/objects/0/a/4/dataset_0a442340-e9ec-4c25-ad72-3fd80287970a.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 10,000 reads, 10,000 reads pseudoaligned[quant] estimated average fragment length: 178.097[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 62 rounds[  bam] writing pseudoalignments to BAM format .. done[  bam] sorting BAM files .. done[  bam] indexing BAM file .. done
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #1)" name="0" time="42.71873593330383">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*0.95] collected minimizers[M::mm_idx_gen::0.006*1.63] sorted minimizers[M::main::0.006*1.62] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.006*1.62] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.006*1.60] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.009*1.46] mapped 100 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/f/3/4/dataset_f34b57e9-eb04-40a9-b8c0-855a6c4da8d3.dat[M::main] Real time: 0.011 sec; CPU: 0.014 sec; Peak RSS: 0.005 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #2)" name="1" time="39.727606534957886">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.005*0.97] collected minimizers[M::mm_idx_gen::0.006*1.46] sorted minimizers[M::main::0.006*1.45] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.006*1.45] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.007*1.42] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.010*1.65] mapped 100 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/3/8/4/dataset_3842fcce-e1f1-4ccf-9683-45fd9bf7e1a3.dat[M::main] Real time: 0.011 sec; CPU: 0.017 sec; Peak RSS: 0.004 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #11)" name="10" time="41.291208028793335">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.021*0.96] collected minimizers[M::mm_idx_gen::0.027*2.05] sorted minimizers[M::main::0.027*2.05] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.029*1.98] mid_occ = 62[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.030*1.93] distinct minimizers: 44423 (93.60% are singletons); average occurrences: 1.142; average spacing: 9.827; total length: 498556[M::worker_pipeline::0.066*2.18] mapped 234 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x map-hifi --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/1/c/0/dataset_1c0dde1e-fdfa-49c9-8af8-bfe94245c734.dat[M::main] Real time: 0.073 sec; CPU: 0.150 sec; Peak RSS: 0.011 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #12)" name="11" time="40.15057992935181">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*0.94] collected minimizers[M::mm_idx_gen::0.006*1.94] sorted minimizers[M::main::0.006*1.93] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.006*1.93] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.006*1.88] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.009*1.85] mapped 100 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -U 10,30 -t 8 -a reference.fa /galaxy/server/database/objects/a/0/0/dataset_a00431a1-926c-4b35-afaa-be232ffdf40e.dat[M::main] Real time: 0.011 sec; CPU: 0.018 sec; Peak RSS: 0.005 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #3)" name="2" time="45.37587356567383">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*1.01] collected minimizers[M::mm_idx_gen::0.006*1.80] sorted minimizers[M::main::0.006*1.80] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.006*1.80] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.007*1.76] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.013*2.15] mapped 200 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/7/d/5/dataset_7d5059b5-175e-46ae-a3dc-6a638c6a56ed.dat /galaxy/server/database/objects/0/4/b/dataset_04b6c905-c734-409c-8e89-680c5cb6d1db.dat[M::main] Real time: 0.015 sec; CPU: 0.029 sec; Peak RSS: 0.005 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #4)" name="3" time="24.108911752700806">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 3, "time_seconds": 24.108911752700806, "tool_id": "minimap2", "tool_version": "2.28+galaxy2"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #5)" name="4" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 4, "tool_id": "minimap2", "tool_version": "2.28+galaxy2"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #6)" name="5" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 5, "tool_id": "minimap2", "tool_version": "2.28+galaxy2"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #7)" name="6" time="37.24371862411499">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.018*0.96] collected minimizers[M::mm_idx_gen::0.028*2.85] sorted minimizers[M::main::0.028*2.85] loaded/built the index for 25 target sequence(s)[M::mm_mapopt_update::0.031*2.66] mid_occ = 10[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25[M::mm_idx_stat::0.033*2.55] distinct minimizers: 80111 (99.87% are singletons); average occurrences: 1.002; average spacing: 2.935; total length: 235533[M::worker_pipeline::0.040*2.75] mapped 25 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x ava-ont --q-occ-frac 0.01 -t 8 reference.fa /galaxy/server/database/objects/9/7/e/dataset_97e71d55-b698-4af2-9af5-ed8b74faab6d.dat[M::main] Real time: 0.045 sec; CPU: 0.115 sec; Peak RSS: 0.012 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #8)" name="7" time="11.699440717697144">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 7, "time_seconds": 11.699440717697144, "tool_id": "minimap2", "tool_version": "2.28+galaxy2"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #9)" name="8" time="38.39587712287903">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.005*1.06] collected minimizers[M::mm_idx_gen::0.007*1.81] sorted minimizers[M::main::0.007*1.81] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.007*1.80] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.007*1.78] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.009*1.96] mapped 100 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 --mask-len 100 -t 8 -a reference.fa /galaxy/server/database/objects/0/2/f/dataset_02fbf42f-13c7-4138-899e-355ae0c49c0d.dat[M::main] Real time: 0.011 sec; CPU: 0.019 sec; Peak RSS: 0.005 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #10)" name="9" time="13.880984783172607">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 9, "time_seconds": 13.880984783172607, "tool_id": "minimap2", "tool_version": "2.28+galaxy2"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="mummer_dnadiff (Test #1)" name="0" time="50.87344455718994">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Building alignmentsFiltering alignmentsExtracting alignment coordinatesAnalyzing SNPsExtracting alignment breakpointsGenerating report file
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="pileup_interval (Test #1)" name="0" time="38.76656126976013">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="pileup_interval (Test #2)" name="1" time="37.61421728134155">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="pileup_interval (Test #3)" name="2" time="36.99792242050171">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_squiggle (Test #1)" name="0" time="80.40427780151367">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_squiggle (Test #2)" name="1" time="50.30601477622986">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #1)" name="0" time="46.326170444488525">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #2)" name="1" time="29.072055101394653">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "cond_region|region": "eboVir3:500-1500",  "cond_region|select_region": "text",  "input_bams": {   "id": "3a99e30e94ce9bb0",   "src": "hda"  } }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/4/3/c/dataset_43c8aaf7-e767-4d70-9b02-fb79a1395cef.dat\u0027 \u00270\u0027 \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/_metadata_files/a/8/d/metadata_a8d517ce-f52a-44f6-92b0-6699132c20bb.dat\u0027 \u00270.bai\u0027 \u0026\u0026   samtools depth  -r eboVir3:500-1500 0 \u003e \u0027/galaxy/server/database/objects/5/e/4/dataset_5e41555b-cf57-4933-910b-a07c8e639609.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-24T01:09:26.245064",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-54fpw",  "galaxy_version": "24.1",  "handler": null,  "history_id": "3b4cd3e794c37e3e",  "id": "decb930df38263ea",  "inputs": {   "input_bams": {    "id": "3a99e30e94ce9bb0",    "src": "hda",    "uuid": "43c8aaf7-e767-4d70-9b02-fb79a1395cef"   },   "input_bams1": {    "id": "3a99e30e94ce9bb0",    "src": "hda",    "uuid": "43c8aaf7-e767-4d70-9b02-fb79a1395cef"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "decb930df38263ea",    "src": "hda",    "uuid": "5e41555b-cf57-4933-910b-a07c8e639609"   }  },  "params": {   "__input_ext": "\"bam\"",   "all": "\"\"",   "basequality": "\"\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "cond_region": "{\"__current_case__\": 1, \"region\": \"eboVir3:500-1500\", \"select_region\": \"text\"}",   "dbkey": "\"?\"",   "mapquality": "\"\"",   "maxdepth": "\"\"",   "minlength": "\"\""  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/samtools_depth/samtools_depth/1.9",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-24T01:09:31.978693",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/samtools_depth/samtools_depth/1.9, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/samtools_depth/samtools_depth/1.9, exit_code: None, stderr: ." ], "status": "failure", "test_index": 1, "time_seconds": 29.072055101394653, "tool_id": "samtools_depth", "tool_version": "1.9"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #3)" name="2" time="13.806454181671143">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 2, "time_seconds": 13.806454181671143, "tool_id": "samtools_depth", "tool_version": "1.9"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #4)" name="3" time="30.24689269065857">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "basequality": "11",  "input_bams": [   {    "id": "9c358160111b95fa",    "src": "hda"   },   {    "id": "1502db8a4065064b",    "src": "hda"   }  ],  "mapquality": "12",  "maxdepth": "4",  "minlength": "10" }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/c/3/e/dataset_c3eefb8d-ce21-40b2-bcf8-ad4f5cf15dd9.dat\u0027 \u00270\u0027 \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/_metadata_files/e/c/4/metadata_ec4d1cc3-412b-4d76-9fcd-0f34f234336f.dat\u0027 \u00270.bai\u0027 \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/2/9/f/dataset_29f39186-c1f9-4b55-a605-4dbfdf680447.dat\u0027 \u00271\u0027 \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/_metadata_files/4/1/0/metadata_410c6364-c50b-46af-a4a2-26e02ca184c5.dat\u0027 \u00271.bai\u0027 \u0026\u0026   samtools depth  -l 10 -m 4 -q 11 -Q 12 0 1 \u003e \u0027/galaxy/server/database/objects/d/c/2/dataset_dc2f1d17-fd6c-4575-8edc-2031eec26b4b.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-24T01:10:11.197470",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-cr6vq",  "galaxy_version": "24.1",  "handler": null,  "history_id": "3b4cd3e794c37e3e",  "id": "01020e65069d3c45",  "inputs": {   "input_bams": {    "id": "9c358160111b95fa",    "src": "hda",    "uuid": "c3eefb8d-ce21-40b2-bcf8-ad4f5cf15dd9"   },   "input_bams1": {    "id": "9c358160111b95fa",    "src": "hda",    "uuid": "c3eefb8d-ce21-40b2-bcf8-ad4f5cf15dd9"   },   "input_bams2": {    "id": "1502db8a4065064b",    "src": "hda",    "uuid": "29f39186-c1f9-4b55-a605-4dbfdf680447"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "01020e65069d3c45",    "src": "hda",    "uuid": "dc2f1d17-fd6c-4575-8edc-2031eec26b4b"   }  },  "params": {   "__input_ext": "\"bam\"",   "all": "\"\"",   "basequality": "\"11\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "cond_region": "{\"__current_case__\": 0, \"select_region\": \"no\"}",   "dbkey": "\"?\"",   "mapquality": "\"12\"",   "maxdepth": "\"4\"",   "minlength": "\"10\""  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/samtools_depth/samtools_depth/1.9",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-24T01:10:16.186210",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/samtools_depth/samtools_depth/1.9, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/samtools_depth/samtools_depth/1.9, exit_code: None, stderr: ." ], "status": "failure", "test_index": 3, "time_seconds": 30.24689269065857, "tool_id": "samtools_depth", "tool_version": "1.9"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_rmdup (Test #1)" name="0" time="44.94998025894165">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [bam_rmdup_core] processing reference chrM...
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcfcombine (Test #1)" name="0" time="52.37685441970825">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
</testsuite>