<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Results (powered by Planemo)"
           tests="65"
           errors="16"
           failures="5"
           skip="0">
    
    <testcase classname="bcftools_filter (Test #1)" name="0" time="38.85165500640869">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #2)" name="1" time="31.90744972229004">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #11)" name="10" time="32.79876923561096">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #3)" name="2" time="33.794639110565186">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #4)" name="3" time="11.96107292175293">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 3, "time_seconds": 11.96107292175293, "tool_id": "bcftools_filter", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #5)" name="4" time="32.053020000457764">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #6)" name="5" time="24.35735583305359">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input_file": {   "id": "e5482e3d4110cfa8",   "src": "hda"  },  "output_type": "v",  "sec_filter|conditional_soft_filter|selector": "enabled",  "sec_filter|conditional_soft_filter|soft_filter": "XX",  "sec_restrict|exclude": "INFO/DP=19" }, "job": {  "command_line": "export BCFTOOLS_PLUGINS=`which bcftools | sed \u0027s,bin/bcftools,libexec/bcftools,\u0027`;     bgzip -c \u0027/galaxy/server/database/objects/5/d/2/dataset_5d2e6c75-cff2-4f8a-8000-42b625e8b143.dat\u0027 \u003e input.vcf.gz \u0026\u0026 bcftools index input.vcf.gz \u0026\u0026            bcftools filter  --soft-filter \u0027XX\u0027                   --exclude \u0027INFO/DP=19\u0027    --output-type \u0027v\u0027   --threads ${GALAXY_SLOTS:-4}    input.vcf.gz  \u003e \u0027/galaxy/server/database/objects/d/8/9/dataset_d8963ebd-3c67-40f7-83f8-a7fc072dc4c3.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-03T01:21:41.334237",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-pn82c",  "galaxy_version": "24.1",  "handler": null,  "history_id": "402a26e552d528ae",  "id": "da548c296881ed66",  "inputs": {   "input_file": {    "id": "e5482e3d4110cfa8",    "src": "hda",    "uuid": "5d2e6c75-cff2-4f8a-8000-42b625e8b143"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output_file": {    "id": "da548c296881ed66",    "src": "hda",    "uuid": "d8963ebd-3c67-40f7-83f8-a7fc072dc4c3"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "output_type": "\"v\"",   "sec_filter": "{\"IndelGap\": \"\", \"SnpGap\": \"\", \"conditional_soft_filter\": {\"__current_case__\": 1, \"masks\": {\"__current_case__\": 0, \"masks_src\": \"__none__\"}, \"masks_overlap\": null, \"selector\": \"enabled\", \"soft_filter\": \"XX\"}, \"mode\": null, \"select_set_GTs\": null}",   "sec_restrict": "{\"exclude\": \"INFO/DP=19\", \"include\": null, \"regions\": {\"__current_case__\": 0, \"regions_src\": \"__none__\"}, \"regions_overlap\": null, \"targets\": {\"__current_case__\": 0, \"targets_src\": \"__none__\"}, \"targets_overlap\": null}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/bcftools_filter/bcftools_filter/1.15.1+galaxy4",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-03T01:21:47.065218",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/bcftools_filter/bcftools_filter/1.15.1+galaxy4, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/bcftools_filter/bcftools_filter/1.15.1+galaxy4, exit_code: None, stderr: ." ], "status": "failure", "test_index": 5, "time_seconds": 24.35735583305359, "tool_id": "bcftools_filter", "tool_version": "1.15.1+galaxy4"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #7)" name="6" time="32.090970516204834">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #8)" name="7" time="32.38081455230713">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #9)" name="8" time="32.65892720222473">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_filter (Test #10)" name="9" time="32.08894896507263">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #1)" name="0" time="42.799368381500244">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 1 samples in 1 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #2)" name="1" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 1, "tool_id": "bcftools_mpileup", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #3)" name="2" time="19.00864005088806">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 2, "time_seconds": 19.00864005088806, "tool_id": "bcftools_mpileup", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #4)" name="3" time="25.033390998840332">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 3, "time_seconds": 25.033390998840332, "tool_id": "bcftools_mpileup", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #5)" name="4" time="42.899121046066284">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [warning] tag DV functional, but deprecated. Please switch to `AD` in future.[mpileup] 3 samples in 3 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #6)" name="5" time="43.80558109283447">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 3 samples in 3 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_mpileup (Test #7)" name="6" time="34.728336811065674">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 1 samples in 1 input files[mpileup] maximum number of reads per input file set to -d 250
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #1)" name="0" time="0.10356426239013672">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 163, in stage_data_in_history
    test_dict = galaxy_interactor.remote_to_input(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 582, in remote_to_input
    path_or_location = self._get_path_or_location(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 619, in _get_path_or_location
    path = self.test_data_download(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 525, in test_data_download
    raise AssertionError(f"Test input file ({filename}) cannot be found.")
AssertionError: Test input file (group_compute_input.txt) cannot be found.
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 163, in stage_data_in_history\n    test_dict = galaxy_interactor.remote_to_input(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 582, in remote_to_input\n    path_or_location = self._get_path_or_location(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 619, in _get_path_or_location\n    path = self.test_data_download(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 525, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nAssertionError: Test input file (group_compute_input.txt) cannot be found.\n", "status": "error", "test_index": 0, "time_seconds": 0.10356426239013672, "tool_id": "datamash_ops", "tool_version": "1.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #2)" name="1" time="0.05372881889343262">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 163, in stage_data_in_history
    test_dict = galaxy_interactor.remote_to_input(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 582, in remote_to_input
    path_or_location = self._get_path_or_location(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 619, in _get_path_or_location
    path = self.test_data_download(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 525, in test_data_download
    raise AssertionError(f"Test input file ({filename}) cannot be found.")
AssertionError: Test input file (group_compute_input.txt) cannot be found.
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 163, in stage_data_in_history\n    test_dict = galaxy_interactor.remote_to_input(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 582, in remote_to_input\n    path_or_location = self._get_path_or_location(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 619, in _get_path_or_location\n    path = self.test_data_download(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 525, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nAssertionError: Test input file (group_compute_input.txt) cannot be found.\n", "status": "error", "test_index": 1, "time_seconds": 0.05372881889343262, "tool_id": "datamash_ops", "tool_version": "1.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #3)" name="2" time="0.05564618110656738">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 163, in stage_data_in_history
    test_dict = galaxy_interactor.remote_to_input(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 582, in remote_to_input
    path_or_location = self._get_path_or_location(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 619, in _get_path_or_location
    path = self.test_data_download(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 525, in test_data_download
    raise AssertionError(f"Test input file ({filename}) cannot be found.")
AssertionError: Test input file (group_compute_input.csv) cannot be found.
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 163, in stage_data_in_history\n    test_dict = galaxy_interactor.remote_to_input(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 582, in remote_to_input\n    path_or_location = self._get_path_or_location(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 619, in _get_path_or_location\n    path = self.test_data_download(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 525, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nAssertionError: Test input file (group_compute_input.csv) cannot be found.\n", "status": "error", "test_index": 2, "time_seconds": 0.05564618110656738, "tool_id": "datamash_ops", "tool_version": "1.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="datamash_ops (Test #4)" name="3" time="0.05616021156311035">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 163, in stage_data_in_history
    test_dict = galaxy_interactor.remote_to_input(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 582, in remote_to_input
    path_or_location = self._get_path_or_location(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 619, in _get_path_or_location
    path = self.test_data_download(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 525, in test_data_download
    raise AssertionError(f"Test input file ({filename}) cannot be found.")
AssertionError: Test input file (na_values_input.tsv) cannot be found.
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 163, in stage_data_in_history\n    test_dict = galaxy_interactor.remote_to_input(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 582, in remote_to_input\n    path_or_location = self._get_path_or_location(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 619, in _get_path_or_location\n    path = self.test_data_download(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 525, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nAssertionError: Test input file (na_values_input.tsv) cannot be found.\n", "status": "error", "test_index": 3, "time_seconds": 0.05616021156311035, "tool_id": "datamash_ops", "tool_version": "1.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="deeptools_bam_pe_fragmentsize (Test #1)" name="0" time="46.7335045337677">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "histogram": true,  "multibam_conditional|bamfiles": {   "id": "446735bbe674a2fb",   "src": "hda"  },  "plotTitle": "Test Plot" }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/e/d/3/dataset_ed3728c9-d30f-4d55-a291-58dd9b3b7104.dat\u0027 \u0027./0.bam\u0027 \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/_metadata_files/8/a/b/metadata_8abb54d7-4e1a-46e6-b2f1-27d5de10235d.dat\u0027 \u0027./0.bam.bai\u0027 \u0026\u0026   bamPEFragmentSize --numberOfProcessors \"${GALAXY_SLOTS:-4}\" --bamfiles \u00270.bam\u0027 --samplesLabel \u0027bowtie2 test1.bam\u0027 --histogram \u0027/galaxy/server/database/objects/5/2/9/dataset_52984c7c-f439-4842-86b9-8c918b66e85f.dat\u0027 --plotFileFormat \u0027png\u0027 --plotTitle \u0027Test Plot\u0027 \u003e \u0027/galaxy/server/database/objects/9/9/4/dataset_994d4331-1d3f-45ab-86a6-9b662bfebe1d.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-03T01:27:26.060485",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-gs5kp",  "galaxy_version": "24.1",  "handler": null,  "history_id": "402a26e552d528ae",  "id": "a4e5671469cdbd3d",  "inputs": {   "multibam_conditional|bamfiles": {    "id": "446735bbe674a2fb",    "src": "hda",    "uuid": "ed3728c9-d30f-4d55-a291-58dd9b3b7104"   },   "multibam_conditional|bamfiles1": {    "id": "446735bbe674a2fb",    "src": "hda",    "uuid": "ed3728c9-d30f-4d55-a291-58dd9b3b7104"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "fragLengths": {    "id": "bac3c8e0caaa0f72",    "src": "hda",    "uuid": "86c5fc6a-b3b9-4439-98ad-852e24c02d54"   },   "histogram_outfile": {    "id": "daaf13066247b9de",    "src": "hda",    "uuid": "52984c7c-f439-4842-86b9-8c918b66e85f"   },   "outfile": {    "id": "5d6cccc16770743c",    "src": "hda",    "uuid": "994d4331-1d3f-45ab-86a6-9b662bfebe1d"   },   "table": {    "id": "2435e983e02c902f",    "src": "hda",    "uuid": "3cf1d5d3-48b6-4d72-a95c-7fd4060d3b6b"   }  },  "params": {   "__input_ext": "\"input\"",   "advancedOpt": "{\"__current_case__\": 0, \"showAdvancedOpt\": \"no\"}",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "custom_sample_labels_conditional": "{\"__current_case__\": 0, \"custom_labels_select\": \"No\"}",   "dbkey": "\"?\"",   "histogram": "true",   "multibam_conditional": "{\"__current_case__\": 0, \"bamfiles\": {\"values\": [{\"id\": 76, \"src\": \"hda\"}]}, \"orderMatters\": \"No\"}",   "outFileFormat": "\"png\"",   "plotTitle": "\"Test Plot\"",   "samplesLabel": null  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bam_pe_fragmentsize/deeptools_bam_pe_fragmentsize/3.5.4+galaxy0",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-03T01:27:53.286887",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bam_pe_fragmentsize/deeptools_bam_pe_fragmentsize/3.5.4+galaxy0, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bam_pe_fragmentsize/deeptools_bam_pe_fragmentsize/3.5.4+galaxy0, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bam_pe_fragmentsize/deeptools_bam_pe_fragmentsize/3.5.4+galaxy0, exit_code: None, stderr: ." ], "status": "failure", "test_index": 0, "time_seconds": 46.7335045337677, "tool_id": "deeptools_bam_pe_fragmentsize", "tool_version": "3.5.4+galaxy0"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="deeptools_bam_pe_fragmentsize (Test #2)" name="1" time="42.75608777999878">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #1)" name="0" time="47.32562327384949">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #2)" name="1" time="35.41418766975403">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #3)" name="2" time="19.169578075408936">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 2, "time_seconds": 19.169578075408936, "tool_id": "freebayes", "tool_version": "1.3.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="freebayes (Test #4)" name="3" time="36.20824956893921">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #5)" name="4" time="20.1401309967041">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 4, "time_seconds": 20.1401309967041, "tool_id": "freebayes", "tool_version": "1.3.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="freebayes (Test #6)" name="5" time="33.60393166542053">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #7)" name="6" time="33.99320983886719">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="freebayes (Test #8)" name="7" time="11.637332677841187">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 7, "time_seconds": 11.637332677841187, "tool_id": "freebayes", "tool_version": "1.3.8+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #1)" name="0" time="42.42473101615906">
        
            
            <system-out><![CDATA[
            {"n_targets": 1,"n_bootstraps": 0,"n_processed": 100,"n_pseudoaligned": 100,"n_unique": 100,"p_pseudoaligned": 100.0,"p_unique": 100.0,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug  3 01:39:05 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . /galaxy/server/database/objects/7/7/5/dataset_77533515-0984-41e1-a8db-8c1b9221ad0d.dat /galaxy/server/database/objects/7/1/a/dataset_71ae74d6-b2da-43d2-add8-ad2c2f695f65.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 1[index] number of k-mers: 16,269[index] number of equivalence classes: 1[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/7/7/5/dataset_77533515-0984-41e1-a8db-8c1b9221ad0d.dat                             /galaxy/server/database/objects/7/1/a/dataset_71ae74d6-b2da-43d2-add8-ad2c2f695f65.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 100 reads, 100 reads pseudoaligned[quant] estimated average fragment length: 499.12[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 52 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #2)" name="1" time="31.497916221618652">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "reference_transcriptome|reference": {   "id": "9d63a61daf488f96",   "src": "hda"  },  "reference_transcriptome|reference_transcriptome_source": "history",  "single_paired|forward": {   "id": "2708d2a216f57a74",   "src": "hda"  },  "single_paired|lib_type": "--fr-stranded",  "single_paired|reverse": {   "id": "cef094f3a71e0e91",   "src": "hda"  },  "single_paired|single_paired_selector": "paired_single" }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/c/4/8/dataset_c4834cbd-9cf7-4bf9-b600-1309fd160e0e.dat\u0027 reference.fa \u0026\u0026 kallisto index reference.fa -i reference.kallisto \u0026\u0026 kallisto quant -i \u0027reference.kallisto\u0027 --bootstrap-samples 0 --seed 42 --threads ${GALAXY_SLOTS:-1} -o . --fr-stranded \u0027/galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat\u0027 \u0027/galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat\u0027  \u0026\u0026 cat run_info.json",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-03T01:39:42.322962",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-bb8wd",  "galaxy_version": "24.1",  "handler": null,  "history_id": "402a26e552d528ae",  "id": "9fd6655fe623d92b",  "inputs": {   "reference_transcriptome|reference": {    "id": "9d63a61daf488f96",    "src": "hda",    "uuid": "c4834cbd-9cf7-4bf9-b600-1309fd160e0e"   },   "single_paired|forward": {    "id": "2708d2a216f57a74",    "src": "hda",    "uuid": "b651eacb-da9a-4fae-80df-c10a805b33d6"   },   "single_paired|reverse": {    "id": "cef094f3a71e0e91",    "src": "hda",    "uuid": "07961319-8167-44e3-a6c5-8fd621496c4a"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "abundance_h5": {    "id": "c07252bb19192874",    "src": "hda",    "uuid": "903765d5-6804-44bc-82ff-2a3ac7c5cba8"   },   "abundance_tab": {    "id": "ac6833a0af20731b",    "src": "hda",    "uuid": "857b6583-c52e-4601-9711-e7de733ed471"   }  },  "params": {   "__input_ext": "\"input\"",   "bias": "false",   "bootstrap_samples": "\"0\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "fusion": "false",   "genomebam_option": "{\"__current_case__\": 1, \"selector\": \"\"}",   "pseudobam": "false",   "reference_transcriptome": "{\"__current_case__\": 1, \"reference\": {\"values\": [{\"id\": 143, \"src\": \"hda\"}]}, \"reference_transcriptome_source\": \"history\"}",   "seed": "\"42\"",   "single_overhang": "false",   "single_paired": "{\"__current_case__\": 1, \"forward\": {\"values\": [{\"id\": 144, \"src\": \"hda\"}]}, \"lib_type\": \"--fr-stranded\", \"reverse\": {\"values\": [{\"id\": 145, \"src\": \"hda\"}]}, \"single_paired_selector\": \"paired_single\"}"  },  "state": "error",  "stderr": "\n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 1\n[index] number of k-mers: 16,269\n[index] number of equivalence classes: 1\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat\n                             /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 100 reads, 37 reads pseudoaligned\n[quant] estimated average fragment length: 495.838\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 52 rounds\n\n",  "stdout": "{\n\t\"n_targets\": 1,\n\t\"n_bootstraps\": 0,\n\t\"n_processed\": 100,\n\t\"n_pseudoaligned\": 37,\n\t\"n_unique\": 37,\n\t\"p_pseudoaligned\": 37.0,\n\t\"p_unique\": 37.0,\n\t\"kallisto_version\": \"0.48.0\",\n\t\"index_version\": 10,\n\t\"start_time\": \"Sun Aug  3 01:39:44 2025\",\n\t\"call\": \"kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . --fr-stranded /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat\"\n}\n",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/kallisto_quant/kallisto_quant/0.48.0+galaxy1",  "tool_stderr": "\n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 1\n[index] number of k-mers: 16,269\n[index] number of equivalence classes: 1\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat\n                             /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 100 reads, 37 reads pseudoaligned\n[quant] estimated average fragment length: 495.838\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 52 rounds\n\n",  "tool_stdout": "{\n\t\"n_targets\": 1,\n\t\"n_bootstraps\": 0,\n\t\"n_processed\": 100,\n\t\"n_pseudoaligned\": 37,\n\t\"n_unique\": 37,\n\t\"p_pseudoaligned\": 37.0,\n\t\"p_unique\": 37.0,\n\t\"kallisto_version\": \"0.48.0\",\n\t\"index_version\": 10,\n\t\"start_time\": \"Sun Aug  3 01:39:44 2025\",\n\t\"call\": \"kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . --fr-stranded /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat\"\n}\n",  "update_time": "2025-08-03T01:39:48.199761",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/kallisto_quant/kallisto_quant/0.48.0+galaxy1, exit_code: None, stderr: \n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 1\n[index] number of k-mers: 16,269\n[index] number of equivalence classes: 1\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat\n                             /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 100 reads, 37 reads pseudoaligned\n[quant] estimated average fragment length: 495.838\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 52 rounds\n\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/kallisto_quant/kallisto_quant/0.48.0+galaxy1, exit_code: None, stderr: \n[build] loading fasta file reference.fa\n[build] k-mer length: 31\n[build] counting k-mers ... done.\n[build] building target de Bruijn graph ...  done \n[build] creating equivalence classes ...  done\n[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers \n\n\n[quant] fragment length distribution will be estimated from the data\n[index] k-mer length: 31\n[index] number of targets: 1\n[index] number of k-mers: 16,269\n[index] number of equivalence classes: 1\n[quant] running in paired-end mode\n[quant] will process pair 1: /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat\n                             /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat\n[quant] finding pseudoalignments for the reads ... done\n[quant] processed 100 reads, 37 reads pseudoaligned\n[quant] estimated average fragment length: 495.838\n[   em] quantifying the abundances ... done\n[   em] the Expectation-Maximization algorithm ran for 52 rounds\n\n." ], "status": "failure", "test_index": 1, "time_seconds": 31.497916221618652, "tool_id": "kallisto_quant", "tool_version": "0.48.0+galaxy1"}
                ]]></error>
            
            <system-out><![CDATA[
            {"n_targets": 1,"n_bootstraps": 0,"n_processed": 100,"n_pseudoaligned": 37,"n_unique": 37,"p_pseudoaligned": 37.0,"p_unique": 37.0,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug  3 01:39:44 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . --fr-stranded /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 1[index] number of k-mers: 16,269[index] number of equivalence classes: 1[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/b/6/5/dataset_b651eacb-da9a-4fae-80df-c10a805b33d6.dat                             /galaxy/server/database/objects/0/7/9/dataset_07961319-8167-44e3-a6c5-8fd621496c4a.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 100 reads, 37 reads pseudoaligned[quant] estimated average fragment length: 495.838[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 52 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #3)" name="2" time="10.930630207061768">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 2, "time_seconds": 10.930630207061768, "tool_id": "kallisto_quant", "tool_version": "0.48.0+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #4)" name="3" time="36.12346124649048">
        
            
            <system-out><![CDATA[
            {"n_targets": 1,"n_bootstraps": 0,"n_processed": 100,"n_pseudoaligned": 100,"n_unique": 100,"p_pseudoaligned": 100.0,"p_unique": 100.0,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug  3 01:40:23 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . --single --fragment-length 200 --sd 20 /galaxy/server/database/objects/4/2/3/dataset_4239eabc-61de-4390-aeaa-6ea75294aeb4.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1 contigs and contains 16269 k-mers [quant] fragment length distribution is truncated gaussian with mean = 200, sd = 20[index] k-mer length: 31[index] number of targets: 1[index] number of k-mers: 16,269[index] number of equivalence classes: 1[quant] running in single-end mode[quant] will process file 1: /galaxy/server/database/objects/4/2/3/dataset_4239eabc-61de-4390-aeaa-6ea75294aeb4.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 100 reads, 100 reads pseudoaligned[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 52 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #5)" name="4" time="11.986336708068848">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 4, "time_seconds": 11.986336708068848, "tool_id": "kallisto_quant", "tool_version": "0.48.0+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #6)" name="5" time="22.675410985946655">
        
            <error type="error" message="parameter 'index': an invalid option (None) was selected, please verify"><![CDATA[
                { "dynamic_param_error": true, "execution_problem": "parameter \u0027index\u0027: an invalid option (None) was selected, please verify", "inputs": {  "pseudobam": true,  "single_paired|forward": {   "id": "8650b0ca6ced2bcf",   "src": "hda"  },  "single_paired|reverse": {   "id": "f3a0c033cc5a6165",   "src": "hda"  },  "single_paired|single_paired_selector": "paired_single" }, "status": "error", "test_index": 5, "time_seconds": 22.675410985946655, "tool_id": "kallisto_quant", "tool_version": "0.48.0+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #7)" name="6" time="41.389639139175415">
        
            
            <system-out><![CDATA[
            {"n_targets": 284,"n_bootstraps": 0,"n_processed": 744,"n_pseudoaligned": 368,"n_unique": 263,"p_pseudoaligned": 49.5,"p_unique": 35.3,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug  3 01:41:39 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --fusion --threads 8 -o . /galaxy/server/database/objects/e/6/b/dataset_e6bf6082-e9a6-4868-9ed8-886c95f92d8e.dat /galaxy/server/database/objects/9/b/f/dataset_9bfcefdb-aa59-4275-a26c-b68441bda2c3.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] warning: clipped off poly-A tail (longer than 10)        from 7 target sequences[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 1179 contigs and contains 216490 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 284[index] number of k-mers: 216,490[index] number of equivalence classes: 909[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/e/6/b/dataset_e6bf6082-e9a6-4868-9ed8-886c95f92d8e.dat                             /galaxy/server/database/objects/9/b/f/dataset_9bfcefdb-aa59-4275-a26c-b68441bda2c3.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 744 reads, 368 reads pseudoaligned[quant] estimated average fragment length: 140.96[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 210 rounds
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="kallisto_quant (Test #8)" name="7" time="58.4119439125061">
        
            
            <system-out><![CDATA[
            {"n_targets": 15,"n_bootstraps": 0,"n_processed": 10000,"n_pseudoaligned": 10000,"n_unique": 6937,"p_pseudoaligned": 100.0,"p_unique": 69.4,"kallisto_version": "0.48.0","index_version": 10,"start_time": "Sun Aug  3 01:42:37 2025","call": "kallisto quant -i reference.kallisto --bootstrap-samples 0 --seed 42 --threads 8 -o . --genomebam --gtf /galaxy/server/database/objects/b/4/2/dataset_b42655c1-f911-4ad5-a5f7-298900b0a33a.dat --chromosomes /galaxy/server/database/objects/b/1/8/dataset_b1810097-0e63-4336-b14e-670f6f575aa1.dat /galaxy/server/database/objects/8/0/d/dataset_80d33cfd-5cf8-4857-870c-0378cf0fc50b.dat /galaxy/server/database/objects/5/d/9/dataset_5d957439-d472-4925-a7cf-acac5d995e5f.dat"}
            ]]></system-out>
            <system-err><![CDATA[
            [build] loading fasta file reference.fa[build] k-mer length: 31[build] counting k-mers ... done.[build] building target de Bruijn graph ...  done [build] creating equivalence classes ...  done[build] target de Bruijn graph has 23 contigs and contains 18902 k-mers [quant] fragment length distribution will be estimated from the data[index] k-mer length: 31[index] number of targets: 15[index] number of k-mers: 18,902[index] number of equivalence classes: 22[quant] running in paired-end mode[quant] will process pair 1: /galaxy/server/database/objects/8/0/d/dataset_80d33cfd-5cf8-4857-870c-0378cf0fc50b.dat                             /galaxy/server/database/objects/5/d/9/dataset_5d957439-d472-4925-a7cf-acac5d995e5f.dat[quant] finding pseudoalignments for the reads ... done[quant] processed 10,000 reads, 10,000 reads pseudoaligned[quant] estimated average fragment length: 178.097[   em] quantifying the abundances ... done[   em] the Expectation-Maximization algorithm ran for 62 rounds[  bam] writing pseudoalignments to BAM format .. done[  bam] sorting BAM files .. done[  bam] indexing BAM file .. done
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #1)" name="0" time="18.665090084075928">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 18.665090084075928, "tool_id": "minimap2", "tool_version": "2.28+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #2)" name="1" time="37.69743061065674">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*0.92] collected minimizers[M::mm_idx_gen::0.006*1.40] sorted minimizers[M::main::0.006*1.40] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.006*1.40] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.006*1.38] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.010*1.44] mapped 100 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/a/2/9/dataset_a29c7f21-d0f0-4201-8533-df2b920beb1e.dat[M::main] Real time: 0.012 sec; CPU: 0.016 sec; Peak RSS: 0.004 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #11)" name="10" time="33.790289640426636">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.028*0.96] collected minimizers[M::mm_idx_gen::0.042*2.45] sorted minimizers[M::main::0.042*2.45] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.045*2.37] mid_occ = 50[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.047*2.31] distinct minimizers: 86298 (91.20% are singletons); average occurrences: 1.212; average spacing: 9.858; total length: 1031372[M::worker_pipeline::0.078*2.34] mapped 234 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x map-hifi --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/a/8/b/dataset_a8b19373-b591-4011-8ffb-a9fbab1f4ed2.dat[M::main] Real time: 0.085 sec; CPU: 0.188 sec; Peak RSS: 0.015 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #12)" name="11" time="33.889827728271484">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.015*0.99] collected minimizers[M::mm_idx_gen::0.023*2.44] sorted minimizers[M::main::0.023*2.43] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.024*2.34] mid_occ = 62[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.025*2.28] distinct minimizers: 44423 (93.60% are singletons); average occurrences: 1.142; average spacing: 9.827; total length: 498556[M::worker_pipeline::0.056*2.14] mapped 234 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x map-hifi --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/5/4/a/dataset_54a080f4-c73d-41c2-920f-6aa4f458d38f.dat[M::main] Real time: 0.061 sec; CPU: 0.123 sec; Peak RSS: 0.011 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #13)" name="12" time="20.913320302963257">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 12, "time_seconds": 20.913320302963257, "tool_id": "minimap2", "tool_version": "2.28+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #3)" name="2" time="39.799782037734985">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*0.78] collected minimizers[M::mm_idx_gen::0.006*1.47] sorted minimizers[M::main::0.006*1.47] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.006*1.47] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.007*1.44] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.014*1.89] mapped 200 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/b/1/7/dataset_b170f1a4-4374-4080-839d-9cbcd7674ad9.dat /galaxy/server/database/objects/e/1/3/dataset_e131d30f-e2a6-442a-b527-5ac4af6422af.dat[M::main] Real time: 0.017 sec; CPU: 0.028 sec; Peak RSS: 0.005 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #4)" name="3" time="40.43579626083374">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*0.82] collected minimizers[M::mm_idx_gen::0.006*1.36] sorted minimizers[M::main::0.006*1.36] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.006*1.36] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.006*1.34] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.014*1.51] mapped 200 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/6/8/f/dataset_68fcdde3-fa07-4940-ac2b-7ae8d9fafb80.dat /galaxy/server/database/objects/3/9/f/dataset_39f2cd6b-390d-4c41-bcf2-cf597829a028.dat[M::main] Real time: 0.016 sec; CPU: 0.023 sec; Peak RSS: 0.005 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #5)" name="4" time="39.092976093292236">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.005*0.77] collected minimizers[M::mm_idx_gen::0.008*1.44] sorted minimizers[M::main::0.008*1.43] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.008*1.43] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.008*1.41] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.016*1.70] mapped 200 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/3/1/1/dataset_311f8b8f-7dce-4961-a3b8-d35620b7004f.dat /galaxy/server/database/objects/a/a/7/dataset_aa7f3b05-113d-4cc8-8489-ba38d51634b1.dat[M::main] Real time: 0.019 sec; CPU: 0.029 sec; Peak RSS: 0.005 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #6)" name="5" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 5, "tool_id": "minimap2", "tool_version": "2.28+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #7)" name="6" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 6, "tool_id": "minimap2", "tool_version": "2.28+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #8)" name="7" time="24.622800588607788">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "fastq_input|analysis_type_selector": "ava-ont",  "fastq_input|fastq_input1": {   "id": "6f0df19a5b56c626",   "src": "hda"  },  "fastq_input|fastq_input_selector": "single",  "io_options|output_format": "paf",  "reference_source|ref_file": {   "id": "6f0df19a5b56c626",   "src": "hda"  },  "reference_source|reference_source_selector": "history" }, "job": {  "command_line": "ln -f -s \u0027/galaxy/server/database/objects/8/0/c/dataset_80cf889b-5cce-4a68-9f55-345bfa971d6b.dat\u0027 reference.fa \u0026\u0026 minimap2 -x ava-ont    --q-occ-frac 0.01       -t ${GALAXY_SLOTS:-4} reference.fa \u0027/galaxy/server/database/objects/8/0/c/dataset_80cf889b-5cce-4a68-9f55-345bfa971d6b.dat\u0027 \u003e \u0027/galaxy/server/database/objects/a/b/6/dataset_ab6aee50-b646-4ae7-babb-7194452e739c.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-03T01:31:52.987534",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-kr857",  "galaxy_version": "24.1",  "handler": null,  "history_id": "402a26e552d528ae",  "id": "3f001404730fae5a",  "inputs": {   "fastq_input|fastq_input1": {    "id": "6f0df19a5b56c626",    "src": "hda",    "uuid": "80cf889b-5cce-4a68-9f55-345bfa971d6b"   },   "reference_source|ref_file": {    "id": "6f0df19a5b56c626",    "src": "hda",    "uuid": "80cf889b-5cce-4a68-9f55-345bfa971d6b"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "alignment_output": {    "id": "4351b44568bfc77a",    "src": "hda",    "uuid": "ab6aee50-b646-4ae7-babb-7194452e739c"   }  },  "params": {   "__input_ext": "\"input\"",   "alignment_options": "{\"A\": \"\", \"B\": \"\", \"E\": \"\", \"E2\": \"\", \"O\": \"\", \"O2\": \"\", \"no_end_flt\": true, \"s\": \"\", \"splicing\": {\"__current_case__\": 0, \"splice_mode\": \"preset\"}, \"z\": \"\", \"z2\": \"\"}",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "fastq_input": "{\"__current_case__\": 0, \"analysis_type_selector\": \"ava-ont\", \"fastq_input1\": {\"values\": [{\"id\": 102, \"src\": \"hda\"}]}, \"fastq_input_selector\": \"single\"}",   "indexing_options": "{\"H\": false, \"I\": \"\", \"k\": \"\", \"w\": \"\"}",   "io_options": "{\"K\": \"\", \"L\": false, \"Q\": false, \"Y\": false, \"c\": false, \"cs\": null, \"eqx\": false, \"output_format\": \"paf\"}",   "mapping_options": "{\"F\": \"\", \"N\": \"\", \"X\": false, \"f\": \"\", \"g\": \"\", \"kmer_ocurrence_interval\": {\"__current_case__\": 1, \"interval\": \"\"}, \"m\": \"\", \"mask_len\": \"\", \"max_chain_iter\": \"\", \"max_chain_skip\": \"\", \"min_occ_floor\": \"\", \"n\": \"\", \"p\": \"\", \"q_occ_frac\": \"0.01\", \"r\": \"\"}",   "reference_source": "{\"__current_case__\": 1, \"ref_file\": {\"values\": [{\"id\": 102, \"src\": \"hda\"}]}, \"reference_source_selector\": \"history\"}"  },  "state": "error",  "stderr": "[M::mm_idx_gen::0.017*0.95] collected minimizers\n[M::mm_idx_gen::0.029*2.84] sorted minimizers\n[M::main::0.029*2.84] loaded/built the index for 25 target sequence(s)\n[M::mm_mapopt_update::0.031*2.72] mid_occ = 10\n[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25\n[M::mm_idx_stat::0.033*2.64] distinct minimizers: 80111 (99.87% are singletons); average occurrences: 1.002; average spacing: 2.935; total length: 235533\n[M::worker_pipeline::0.040*2.75] mapped 25 sequences\n[M::main] Version: 2.28-r1209\n[M::main] CMD: minimap2 -x ava-ont --q-occ-frac 0.01 -t 8 reference.fa /galaxy/server/database/objects/8/0/c/dataset_80cf889b-5cce-4a68-9f55-345bfa971d6b.dat\n[M::main] Real time: 0.049 sec; CPU: 0.118 sec; Peak RSS: 0.012 GB\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/2.28+galaxy1",  "tool_stderr": "[M::mm_idx_gen::0.017*0.95] collected minimizers\n[M::mm_idx_gen::0.029*2.84] sorted minimizers\n[M::main::0.029*2.84] loaded/built the index for 25 target sequence(s)\n[M::mm_mapopt_update::0.031*2.72] mid_occ = 10\n[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25\n[M::mm_idx_stat::0.033*2.64] distinct minimizers: 80111 (99.87% are singletons); average occurrences: 1.002; average spacing: 2.935; total length: 235533\n[M::worker_pipeline::0.040*2.75] mapped 25 sequences\n[M::main] Version: 2.28-r1209\n[M::main] CMD: minimap2 -x ava-ont --q-occ-frac 0.01 -t 8 reference.fa /galaxy/server/database/objects/8/0/c/dataset_80cf889b-5cce-4a68-9f55-345bfa971d6b.dat\n[M::main] Real time: 0.049 sec; CPU: 0.118 sec; Peak RSS: 0.012 GB\n",  "tool_stdout": "",  "update_time": "2025-08-03T01:31:58.330844",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/2.28+galaxy1, exit_code: None, stderr: [M::mm_idx_gen::0.017*0.95] collected minimizers\n[M::mm_idx_gen::0.029*2.84] sorted minimizers\n[M::main::0.029*2.84] loaded/built the index for 25 target sequence(s)\n[M::mm_mapopt_update::0.031*2.72] mid_occ = 10\n[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25\n[M::mm_idx_stat::0.033*2.64] distinct minimizers: 80111 (99.87% are singletons); average occurrences: 1.002; average spacing: 2.935; total length: 235533\n[M::worker_pipeline::0.040*2.75] mapped 25 sequences\n[M::main] Version: 2.28-r1209\n[M::main] CMD: minimap2 -x ava-ont --q-occ-frac 0.01 -t 8 reference.fa /galaxy/server/database/objects/8/0/c/dataset_80cf889b-5cce-4a68-9f55-345bfa971d6b.dat\n[M::main] Real time: 0.049 sec; CPU: 0.118 sec; Peak RSS: 0.012 GB\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/2.28+galaxy1, exit_code: None, stderr: [M::mm_idx_gen::0.017*0.95] collected minimizers\n[M::mm_idx_gen::0.029*2.84] sorted minimizers\n[M::main::0.029*2.84] loaded/built the index for 25 target sequence(s)\n[M::mm_mapopt_update::0.031*2.72] mid_occ = 10\n[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25\n[M::mm_idx_stat::0.033*2.64] distinct minimizers: 80111 (99.87% are singletons); average occurrences: 1.002; average spacing: 2.935; total length: 235533\n[M::worker_pipeline::0.040*2.75] mapped 25 sequences\n[M::main] Version: 2.28-r1209\n[M::main] CMD: minimap2 -x ava-ont --q-occ-frac 0.01 -t 8 reference.fa /galaxy/server/database/objects/8/0/c/dataset_80cf889b-5cce-4a68-9f55-345bfa971d6b.dat\n[M::main] Real time: 0.049 sec; CPU: 0.118 sec; Peak RSS: 0.012 GB\n." ], "status": "failure", "test_index": 7, "time_seconds": 24.622800588607788, "tool_id": "minimap2", "tool_version": "2.28+galaxy1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.017*0.95] collected minimizers[M::mm_idx_gen::0.029*2.84] sorted minimizers[M::main::0.029*2.84] loaded/built the index for 25 target sequence(s)[M::mm_mapopt_update::0.031*2.72] mid_occ = 10[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25[M::mm_idx_stat::0.033*2.64] distinct minimizers: 80111 (99.87% are singletons); average occurrences: 1.002; average spacing: 2.935; total length: 235533[M::worker_pipeline::0.040*2.75] mapped 25 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x ava-ont --q-occ-frac 0.01 -t 8 reference.fa /galaxy/server/database/objects/8/0/c/dataset_80cf889b-5cce-4a68-9f55-345bfa971d6b.dat[M::main] Real time: 0.049 sec; CPU: 0.118 sec; Peak RSS: 0.012 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #9)" name="8" time="33.06581234931946">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*0.85] collected minimizers[M::mm_idx_gen::0.007*1.29] sorted minimizers[M::main::0.007*1.29] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.007*1.27] mid_occ = 10[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.007*1.27] distinct minimizers: 2920 (98.42% are singletons); average occurrences: 1.022; average spacing: 10.057; total length: 30000[M::worker_pipeline::0.028*1.06] mapped 1 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -DP -k19 -w19 -m200 --q-occ-frac 0.01 -t 8 -a reference.fa /galaxy/server/database/objects/e/d/a/dataset_edade7ba-b63f-41be-a624-b63ba6b2f94a.dat[M::main] Real time: 0.029 sec; CPU: 0.030 sec; Peak RSS: 0.012 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="minimap2 (Test #10)" name="9" time="32.867886543273926">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [M::mm_idx_gen::0.004*0.98] collected minimizers[M::mm_idx_gen::0.005*1.47] sorted minimizers[M::main::0.005*1.47] loaded/built the index for 1 target sequence(s)[M::mm_mapopt_update::0.005*1.47] mid_occ = 1000[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1[M::mm_idx_stat::0.006*1.44] distinct minimizers: 2777 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.967; total length: 16569[M::worker_pipeline::0.009*1.40] mapped 100 sequences[M::main] Version: 2.28-r1209[M::main] CMD: minimap2 -x sr --q-occ-frac 0.01 --mask-len 100 -t 8 -a reference.fa /galaxy/server/database/objects/0/2/b/dataset_02bf56a0-9ca3-4fd3-8c6f-4f1441737c3f.dat[M::main] Real time: 0.011 sec; CPU: 0.013 sec; Peak RSS: 0.004 GB
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="mummer_dnadiff (Test #1)" name="0" time="41.81138300895691">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Building alignmentsFiltering alignmentsExtracting alignment coordinatesAnalyzing SNPsExtracting alignment breakpointsGenerating report file
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="pileup_interval (Test #1)" name="0" time="18.094298124313354">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 18.094298124313354, "tool_id": "pileup_interval", "tool_version": "1.0.3"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="pileup_interval (Test #2)" name="1" time="33.44431447982788">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="pileup_interval (Test #3)" name="2" time="33.577571630477905">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_squiggle (Test #1)" name="0" time="67.01220273971558">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_squiggle (Test #2)" name="1" time="43.850046157836914">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #1)" name="0" time="89.66839909553528">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #2)" name="1" time="34.230873346328735">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #3)" name="2" time="35.31860089302063">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_depth (Test #4)" name="3" time="34.622729539871216">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_rmdup (Test #1)" name="0" time="28.53329372406006">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "bam_paired_end_type|bam_paired_end_type_selector": "PE",  "bam_paired_end_type|force_se": false,  "input1": {   "id": "e701c3a5b54931dc",   "src": "hda"  } }, "job": {  "command_line": "samtools rmdup  \u0027/galaxy/server/database/objects/5/2/5/dataset_5254c1ac-c1a6-4be3-b17b-6a3b7a528c07.dat\u0027 \u0027/galaxy/server/database/objects/b/c/a/dataset_bcaee461-1fe5-4db8-ada1-923a82a79176.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-03T01:15:13.850398",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-mvnh9",  "galaxy_version": "24.1",  "handler": null,  "history_id": "402a26e552d528ae",  "id": "3e063162ed4f5ac6",  "inputs": {   "input1": {    "id": "e701c3a5b54931dc",    "src": "hda",    "uuid": "5254c1ac-c1a6-4be3-b17b-6a3b7a528c07"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output1": {    "id": "3e063162ed4f5ac6",    "src": "hda",    "uuid": "bcaee461-1fe5-4db8-ada1-923a82a79176"   }  },  "params": {   "__input_ext": "\"bam\"",   "bam_paired_end_type": "{\"__current_case__\": 0, \"bam_paired_end_type_selector\": \"PE\", \"force_se\": false}",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\""  },  "state": "error",  "stderr": "[bam_rmdup_core] processing reference chrM...\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/samtools_rmdup/samtools_rmdup/2.0.1",  "tool_stderr": "[bam_rmdup_core] processing reference chrM...\n",  "tool_stdout": "",  "update_time": "2025-08-03T01:15:22.432103",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_rmdup/samtools_rmdup/2.0.1, exit_code: None, stderr: [bam_rmdup_core] processing reference chrM...\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_rmdup/samtools_rmdup/2.0.1, exit_code: None, stderr: [bam_rmdup_core] processing reference chrM...\n." ], "status": "failure", "test_index": 0, "time_seconds": 28.53329372406006, "tool_id": "samtools_rmdup", "tool_version": "2.0.1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [bam_rmdup_core] processing reference chrM...
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcfcombine (Test #1)" name="0" time="40.61980843544006">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
</testsuite>